// WRM hardware and boot ABI constants. defs.inc mirrors these for assembly;
// tests/test_kernel.py checks their values without generating code.
let BYTE_BITS: UWord = 8
let WORD_BYTES: UWord = 4
let WORD_BITS: UWord = 32
let WORD_MASK: UWord = 0xFFFFFFFF
let INSTRUCTION_BYTES: UWord = WORD_BYTES
let GPR_COUNT: UWord = 32
let REG_RESULT: UWord = 1
let REG_SP: UWord = 30
let REG_RA: UWord = 31
let STACK_ALIGNMENT: UWord = 8
let STACK_ALIGN_MASK: UWord = STACK_ALIGNMENT - 1
let KERNEL_STACK_BYTES: UWord = 8192
let TRAP_DISPATCH_HEADROOM: UWord = 512
// trapBadStack's own stack: the trusted kernel stack failed its checks.
let TRAP_EMERGENCY_STACK_BYTES: UWord = 2048
let STACK_CANARY: UWord = 0x4C414958

let CR_STATUS: UWord = 0
let CR_PTBR: UWord = 6
let STATUS_IE: UWord = 1 << 0
let STATUS_PIE: UWord = 1 << 1
let STATUS_UM: UWord = 1 << 2
let STATUS_PUM: UWord = 1 << 3
let STATUS_EXL: UWord = 1 << 4
let STATUS_SS: UWord = 1 << 5
let STATUS_PSS: UWord = 1 << 6
let STATUS_TRAP_RETURN_MASK: UWord = STATUS_PIE | STATUS_PUM | STATUS_EXL | STATUS_SS | STATUS_PSS
let FCSR_NX: UWord = 1 << 0
let FCSR_ROUND_UP: UWord = 3 << 5

let CAUSE_INTERRUPT: UWord = 0
let CAUSE_ILLEGAL_INSTRUCTION: UWord = 1
let CAUSE_MISALIGNED_FETCH: UWord = 2
let CAUSE_MISALIGNED_LOAD: UWord = 3
let CAUSE_MISALIGNED_STORE: UWord = 4
let CAUSE_FETCH_BUS_ERROR: UWord = 5
let CAUSE_LOAD_BUS_ERROR: UWord = 6
let CAUSE_STORE_BUS_ERROR: UWord = 7
let CAUSE_FETCH_PAGE_FAULT: UWord = 8
let CAUSE_LOAD_PAGE_FAULT: UWord = 9
let CAUSE_STORE_PAGE_FAULT: UWord = 10
let CAUSE_PRIVILEGED_INSTRUCTION: UWord = 11
let CAUSE_SYSCALL: UWord = 12
let CAUSE_BREAKPOINT: UWord = 13
let CAUSE_SINGLE_STEP: UWord = 14
let CAUSE_DEBUG_TRIGGER: UWord = 15
let ERRNO_ENOSYS: Word = 38
let SYSCALL_UNSUPPORTED: UWord = WORD_MASK
let PANIC_EXIT_CODE: UWord = 254

let PAGE_SHIFT: UWord = 12
let PAGE_SIZE: UWord = 1 << PAGE_SHIFT
let PAGE_MASK: UWord = PAGE_SIZE - 1
let PAGE_TABLE_ENTRIES: UWord = PAGE_SIZE / WORD_BYTES
let SUPERPAGE_SHIFT: UWord = 22
let SUPERPAGE_SIZE: UWord = 1 << SUPERPAGE_SHIFT
let PTBR_ENABLE: UWord = 1
let PTE_V: UWord = 1 << 0
let PTE_R: UWord = 1 << 1
let PTE_W: UWord = 1 << 2
let PTE_X: UWord = 1 << 3
let PTE_U: UWord = 1 << 4
let PTE_RWX_BITS: UWord = PTE_R | PTE_W | PTE_X
let PTE_RW: UWord = PTE_V | PTE_R | PTE_W
let PTE_RWX: UWord = PTE_RW | PTE_X
let PTE_RX: UWord = PTE_V | PTE_R | PTE_X
let PTE_RO: UWord = PTE_V | PTE_R
let TLBI_ALL: UWord = 2
let RAM_SLOT_COUNT: UWord = 4
let RAM_SLOT_MAX_BYTES: UWord = 32 * 1024 * 1024
let RAM_MAX_BYTES: UWord = RAM_SLOT_COUNT * RAM_SLOT_MAX_BYTES

let VRAM_BASE: UWord = 0xFC000000
let IO_BASE: UWord = 0xFD000000
let PIC_ENABLE: UWord = IO_BASE + WORD_BYTES
let UART_BASE: UWord = IO_BASE + 2 * PAGE_SIZE
let POWER_BASE: UWord = IO_BASE + 4 * PAGE_SIZE
let DISK0_BASE: UWord = IO_BASE + 5 * PAGE_SIZE
let DISK1_BASE: UWord = IO_BASE + 6 * PAGE_SIZE
let VIDEO_BASE: UWord = IO_BASE + 7 * PAGE_SIZE
let FLOPPY_BASE: UWord = IO_BASE + 8 * PAGE_SIZE
let RNG_BASE: UWord = IO_BASE + 14 * PAGE_SIZE
let RNG_SEEDED: UWord = 1

let BOOT_MAGIC: UWord = 0x424D5257
let BOOT_INFO_MAGIC: UWord = 0x4F464E49
let BOOT_INFO: UWord = 0x1000
let BOOT_INFO_END: UWord = BOOT_INFO + PAGE_SIZE
// Entry state at the end of the boot info page, within the signed offset(r0)
// field. Page zero stays unmapped, so a NULL access faults.
let KERNEL_SP: UWord = BOOT_INFO_END - 4 * WORD_BYTES
let KERNEL_STACK_BOTTOM: UWord = KERNEL_SP + WORD_BYTES
let KERNEL_STACK_TOP: UWord = KERNEL_STACK_BOTTOM + WORD_BYTES
let TRAP_SAVED_R1: UWord = KERNEL_STACK_TOP + WORD_BYTES
// Boot info and its device table must end below the entry state.
let BOOT_INFO_LIMIT: UWord = KERNEL_SP
let BOOT_INFO_BYTES: UWord = BOOT_INFO_LIMIT - BOOT_INFO
let BOOT_INFO_MIN_SIZE: UWord = 40
let BOOT_FIELD_MAGIC: UWord = 0
let BOOT_FIELD_SIZE: UWord = WORD_BYTES
let BOOT_FIELD_RAM_SIZE: UWord = 2 * WORD_BYTES
let BOOT_FIELD_DISK: UWord = 3 * WORD_BYTES
let BOOT_LOAD: UWord = 0x10000
let DEVICE_ENTRY_BYTES: UWord = 2 * WORD_BYTES
let SECTOR_SIZE: UWord = 512
let SECTOR_MASK: UWord = SECTOR_SIZE - 1
let DISK_PRESENT: UWord = 1 << 0
let DISK_BUSY: UWord = 1 << 2
let DISK_DONE: UWord = 1 << 3
let DISK_CHANGED: UWord = 1 << 5
let DISK_READ: UWord = 1

let SCREEN_WIDTH: UWord = 640
let SCREEN_HEIGHT: UWord = 480
let SCREEN_BPP: UWord = 8
let SCREEN_PITCH: UWord = SCREEN_WIDTH * SCREEN_BPP / BYTE_BITS
let CELL_WIDTH: UWord = 8
let GLYPH_HEIGHT: UWord = 16
let GLYPH_WIDTH: UWord = 16
let GLYPH_ROW_BYTES: UWord = GLYPH_WIDTH / BYTE_BITS
let GLYPH_BYTES: UWord = GLYPH_ROW_BYTES * GLYPH_HEIGHT
let VIDEO_BUSY: UWord = 1
let VIDEO_ENABLE: UWord = 1
let VIDEO_MODE_640_480: UWord = 1
let VIDEO_8BPP: UWord = 2 << 4
let VIDEO_XY_SHIFT: UWord = 16
let VIDEO_FILL: UWord = 1
let VIDEO_COPY: UWord = 2
let VIDEO_EXPAND: UWord = 3
let PALETTE_BLACK: UWord = 0
let PALETTE_WHITE: UWord = 0xFFFFFF
let PALETTE_BACKGROUND: UWord = 0
let PALETTE_FOREGROUND: UWord = 1

let UNICODE_MAX: UWord = 0x10FFFF
let UNICODE_SURROGATE_MIN: UWord = 0xD800
let UNICODE_SURROGATE_MAX: UWord = 0xDFFF
let UNICODE_REPLACEMENT: UWord = 0xFFFD

let HEX_DIGIT_BITS: UWord = 4
let HEX_DIGIT_MASK: UWord = (1 << HEX_DIGIT_BITS) - 1
let HEX_WORD_DIGITS: UWord = WORD_BITS / HEX_DIGIT_BITS
let HEX_TOP_SHIFT: UWord = WORD_BITS - HEX_DIGIT_BITS
let DECIMAL_BASE: UWord = 10
let ASCII_ZERO: UWord = 48
let ASCII_HEX_ALPHA_OFFSET: UWord = 55 // 'A' - 10
let ASCII_NEWLINE: UWord = 10

export {
    BYTE_BITS, WORD_BYTES, WORD_BITS, WORD_MASK, INSTRUCTION_BYTES,
    GPR_COUNT, REG_RESULT, REG_SP, REG_RA, STACK_ALIGNMENT, STACK_ALIGN_MASK,
    KERNEL_STACK_BYTES, TRAP_DISPATCH_HEADROOM, TRAP_EMERGENCY_STACK_BYTES, STACK_CANARY,
    CR_STATUS, CR_PTBR, STATUS_IE, STATUS_PIE, STATUS_UM, STATUS_PUM,
    STATUS_EXL, STATUS_SS, STATUS_PSS, STATUS_TRAP_RETURN_MASK,
    FCSR_NX, FCSR_ROUND_UP,
    CAUSE_INTERRUPT, CAUSE_ILLEGAL_INSTRUCTION, CAUSE_MISALIGNED_FETCH,
    CAUSE_MISALIGNED_LOAD, CAUSE_MISALIGNED_STORE, CAUSE_FETCH_BUS_ERROR,
    CAUSE_LOAD_BUS_ERROR, CAUSE_STORE_BUS_ERROR, CAUSE_FETCH_PAGE_FAULT,
    CAUSE_LOAD_PAGE_FAULT, CAUSE_STORE_PAGE_FAULT, CAUSE_PRIVILEGED_INSTRUCTION,
    CAUSE_SYSCALL, CAUSE_BREAKPOINT, CAUSE_SINGLE_STEP, CAUSE_DEBUG_TRIGGER,
    ERRNO_ENOSYS, SYSCALL_UNSUPPORTED, PANIC_EXIT_CODE,
    PAGE_SHIFT, PAGE_SIZE, PAGE_MASK, PAGE_TABLE_ENTRIES, SUPERPAGE_SHIFT,
    SUPERPAGE_SIZE, PTBR_ENABLE, PTE_V, PTE_R, PTE_W, PTE_X, PTE_U,
    PTE_RWX_BITS, PTE_RW, PTE_RWX, PTE_RX, PTE_RO, TLBI_ALL,
    RAM_SLOT_COUNT, RAM_SLOT_MAX_BYTES, RAM_MAX_BYTES,
    VRAM_BASE, IO_BASE, PIC_ENABLE, UART_BASE, POWER_BASE, DISK0_BASE,
    DISK1_BASE, VIDEO_BASE, FLOPPY_BASE, RNG_BASE, RNG_SEEDED,
    BOOT_MAGIC, BOOT_INFO_MAGIC, BOOT_INFO, BOOT_INFO_END, BOOT_INFO_LIMIT, BOOT_INFO_BYTES,
    KERNEL_SP, KERNEL_STACK_BOTTOM, KERNEL_STACK_TOP, TRAP_SAVED_R1,
    BOOT_INFO_MIN_SIZE, BOOT_FIELD_MAGIC, BOOT_FIELD_SIZE, BOOT_FIELD_RAM_SIZE, BOOT_FIELD_DISK,
    BOOT_LOAD, DEVICE_ENTRY_BYTES, SECTOR_SIZE, SECTOR_MASK,
    DISK_PRESENT, DISK_BUSY, DISK_DONE, DISK_CHANGED, DISK_READ,
    SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_BPP, SCREEN_PITCH, CELL_WIDTH, GLYPH_HEIGHT, GLYPH_WIDTH,
    GLYPH_ROW_BYTES, GLYPH_BYTES, VIDEO_BUSY, VIDEO_ENABLE, VIDEO_MODE_640_480,
    VIDEO_8BPP, VIDEO_XY_SHIFT, VIDEO_FILL, VIDEO_COPY, VIDEO_EXPAND,
    PALETTE_BLACK, PALETTE_WHITE, PALETTE_BACKGROUND, PALETTE_FOREGROUND,
    UNICODE_MAX, UNICODE_SURROGATE_MIN, UNICODE_SURROGATE_MAX, UNICODE_REPLACEMENT,
    HEX_DIGIT_BITS, HEX_DIGIT_MASK, HEX_WORD_DIGITS, HEX_TOP_SHIFT,
    DECIMAL_BASE, ASCII_ZERO, ASCII_HEX_ALPHA_OFFSET, ASCII_NEWLINE,
}
