"""Object files: the assembly of one module for tools/asm.py -c, and the
runtime that tools/ld.py links with the modules into an image."""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RUNTIME = os.path.join(ROOT, "m", "runtime")
RUNTIME_M = os.path.join(RUNTIME, "rt.m")  # linked into every program
BOOT_RUNTIME = ("crt0.asm", "trap.asm", "mem.asm")  # crt0 first: it starts the image
ROM_RUNTIME = ("rom0.asm", "trap.asm", "mem.asm")

ROM_RAM_DATA = 0x00002000   # ld.py --data: .data of a ROM runs here
ROM_RAM_LIMIT = 0x0000C000  # .data and .bss end here: 16KB below BOOT_LOAD for the boot stack


class Program:
	"""What the compiler makes of one module: assembly text of the code,
	.rodata and .data, the .bss variables, the assembly files to .include
	after the code and the symbols other object files see."""

	def __init__(self, path):
		self.path = path
		self.code = []
		self.rodata = []
		self.data = []      # (label, size, alignment, assembly of the bytes)
		self.bss = []       # (label, size, alignment)
		self.includes = []  # paths of .asm files
		self.globals = []   # names


def asm_path(path):
	"""A path for .include: absolute, with '/' (asm.py strings take '\\'
	as an escape)."""
	return os.path.abspath(path).replace(os.sep, "/")


def module_asm(program):
	"""The assembly of the module's object file (m/docs/COMPILER.md)."""
	out = [f"; generated by tools/m.py from {program.path}\n\n"]
	for name in program.globals:
		out.append(f"\t.globl {name}\n")
	out.append("\n\t.text\n")
	out += program.code
	for path in program.includes:
		out.append(f'\n\t.text\n\t.include "{asm_path(path)}"\n')
	if program.rodata:
		out.append("\n\t.rodata\n")
		out += program.rodata
	if program.data:
		out.append("\n\t.data\n")
		for label, size, alignment, body in program.data:
			out.append(f"\t.align {alignment}\n{label}:\n{body}")
	if program.bss:
		out.append("\n\t.bss\n")
		for label, size, alignment in program.bss:
			out.append(f"\t.align {alignment}\n{label}:\n\t.space {size}\n")
	return "".join(out)
