"""The boot image: crt0 and the runtime, the program, its data."""

import os

from .typesys import align_up

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RUNTIME = os.path.join(ROOT, "m", "runtime")
RUNTIME_ASM = ("crt0.asm", "mem.asm")  # crt0 first: it starts the image
RUNTIME_M = os.path.join(RUNTIME, "rt.m")  # compiled into every program

SECTOR_SIZE = 512


class Program:
	"""What the compiler hands to the image layout: assembly text of the
	code, .rodata and .data, the .bss variables and the assembly files to
	.include after the code."""

	def __init__(self):
		self.code = []
		self.rodata = []
		self.data = []
		self.bss = []       # (label, size, alignment)
		self.includes = []  # paths of .asm files


def include_path(path, out_dir):
	"""asm.py looks for an .include relative to the including file, so a
	path relative to the output is enough; absolute if there is none (a
	different drive)."""
	path = os.path.realpath(path)
	try:
		path = os.path.relpath(path, os.path.realpath(out_dir))
	except ValueError:
		pass
	return path.replace(os.sep, "/")


def boot_image(program, out_dir):
	"""Returns the assembly of the whole boot image."""
	out = ["; generated by tools/m.py: a boot image, assemble with --base 0x10000\n"]
	for name in RUNTIME_ASM:
		with open(os.path.join(RUNTIME, name), encoding="utf-8") as f:
			out.append(f"\n; ---- m/runtime/{name}\n\n")
			out.append(f.read())

	out.append("\n; ---- code\n\n")
	out += program.code
	for path in program.includes:
		out.append(f'\t.include "{include_path(path, out_dir)}"\n')

	out.append("\n; ---- .rodata\n\n")
	out += program.rodata
	out.append("\n; ---- .data\n\n")
	out += program.data

	# .bss lives past the image, so its variables are just addresses. The
	# image end is aligned for the most aligned of them.
	image_align = max([SECTOR_SIZE] + [a for _, _, a in program.bss])
	out.append(f"\n\t.align {image_align}\n__image_end:\n")
	out.append("\n; ---- .bss\n\n__bss_start = __image_end\n")
	offset = 0
	for label, size, alignment in program.bss:
		offset = align_up(offset, alignment)
		out.append(f"{label} = __bss_start + {offset}\n")
		offset += size
	out.append(f"__bss_end = __bss_start + {align_up(offset, 4)}\n")
	return "".join(out)
