"""The boot image: crt0 and the runtime, the program, its data."""

import os

from .typesys import align_up

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RUNTIME = os.path.join(ROOT, "m", "runtime")
RUNTIME_M = os.path.join(RUNTIME, "rt.m")  # compiled into every program
BOOT_RUNTIME = ("crt0.asm", "trap.asm", "mem.asm")  # crt0 first: it starts the image
ROM_RUNTIME = ("rom0.asm", "trap.asm", "mem.asm")

SECTOR_SIZE = 512
ROM_RAM_DATA = 0x00002000   # rom0.asm: __RAM_DATA
ROM_RAM_LIMIT = 0x0000C000  # .data and .bss end here: 16KB below BOOT_LOAD for the boot stack


class Program:
	"""What the compiler hands to the image layout: assembly text of the
	code, .rodata and .data, the .bss variables and the assembly files to
	.include after the code."""

	def __init__(self):
		self.code = []
		self.rodata = []
		self.data = []      # (label, size, alignment, assembly of the bytes)
		self.bss = []       # (label, size, alignment)
		self.includes = []  # paths of .asm files


def include_path(path, out_dir):
	"""asm.py looks for an .include relative to the including file, so a
	path relative to the output is enough; absolute if there is none (a
	different drive)."""
	path = os.path.realpath(path)
	try:
		path = os.path.relpath(path, os.path.realpath(out_dir))
	except ValueError:
		pass
	return path.replace(os.sep, "/")


def runtime(names):
	out = []
	for name in names:
		with open(os.path.join(RUNTIME, name), encoding="utf-8") as f:
			out.append(f"\n; ---- m/runtime/{name}\n\n")
			out.append(f.read())
	return out


def code_part(program, out_dir):
	out = ["\n; ---- code\n\n"] + program.code
	for path in program.includes:
		out.append(f'\t.include "{include_path(path, out_dir)}"\n')
	out.append("\n; ---- .rodata\n\n")
	return out + program.rodata


def bss_part(program, start):
	"""The .bss variables as addresses from start, which is aligned for
	all of them."""
	out = [f"\n; ---- .bss\n\n__bss_start = {start}\n"]
	offset = 0
	for label, size, alignment in program.bss:
		offset = align_up(offset, alignment)
		out.append(f"{label} = __bss_start + {offset}\n")
		offset += size
	out.append(f"__bss_end = __bss_start + {align_up(offset, 4)}\n")
	return out, offset


def max_align(items):
	return max([4] + [item[2] for item in items])


def boot_image(program, out_dir):
	"""Returns the assembly of a boot image (m/docs/COMPILER.md): it is
	loaded to RAM as a whole, so .data is just part of it."""
	out = ["; generated by tools/m.py: a boot image, assemble with --base 0x10000\n"]
	out += runtime(BOOT_RUNTIME)
	out += code_part(program, out_dir)
	out.append("\n; ---- .data\n\n")
	for label, size, alignment, body in program.data:
		out.append(f"\t.align {alignment}\n{label}:\n{body}")

	# .bss lives past the image, so its variables are just addresses. The
	# image end is aligned for the most aligned of them.
	image_align = max(SECTOR_SIZE, max_align(program.bss))
	out.append(f"\n\t.align {image_align}\n__image_end:\n")
	out += bss_part(program, "__image_end")[0]
	return "".join(out)


def rom_image(program, out_dir):
	"""Returns the assembly of a ROM image (m/docs/COMPILER.md): .data is
	kept in ROM after the constants and copied to RAM by rom0.asm, so its
	labels are RAM addresses. Raises ValueError if .data and .bss don't fit
	below ROM_RAM_LIMIT."""
	out = ["; generated by tools/m.py --rom: a ROM image, assemble at ROM_BASE\n"]
	out += runtime(ROM_RUNTIME)
	out += code_part(program, out_dir)

	# the bytes of .data in ROM, laid out as in RAM: both starts are
	# aligned for every variable
	align = max_align(program.data)
	if ROM_RAM_DATA % align:
		raise ValueError(f"a .data variable aligned to {align} can't go in RAM at "
						 f"0x{ROM_RAM_DATA:X}")
	out.append(f"\n; ---- .data, copied to RAM\n\n\t.align {align}\n__data_load:\n")
	offset = 0
	for label, size, alignment, body in program.data:
		offset = align_up(offset, alignment)
		out.append(f"\t.align {alignment}\n__load__{label}:\n{body}")
		out.append(f"{label} = __data_start + (__load__{label} - __data_load)\n")
		offset += size
	data_size = align_up(offset, 4)
	out.append(f"\t.align 4\n__image_end:\n__data_end = __data_start + {data_size}\n")

	bss_align = max_align(program.bss)
	bss_start = align_up(ROM_RAM_DATA + data_size, bss_align)
	part, bss_size = bss_part(program, f"0x{bss_start:X}")
	out += part
	end = bss_start + bss_size
	if end > ROM_RAM_LIMIT:
		raise ValueError(f".data and .bss take 0x{ROM_RAM_DATA:X} to 0x{end:X} in RAM, past "
						 f"0x{ROM_RAM_LIMIT:X}")
	return "".join(out)
